es-server:
  image: lucasko/elasticsearch
  user: elsearch
  ports:
    - "29200:9200" 
    - "29300:9300" 
  restart: always

jupyter:
  image: lucasko/jupyter
  ports:
    - "8888:8888"
  links:
    - es-server
  command: /bin/bash -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888"
  restart: always

logstash:
  image: logstash
  links:
    - es-server
  volumes:
    - $PWD:/config-dir
  command: -f "/config-dir/logstash.config"
  restart: always

